version: "3"
services:
  application:
    build:
      context: .
      dockerfile: ./dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
    ports:
      - 80:80
    command: php -S 0.0.0.0:80 -t ./application
  
  composer:
    image: composer
    working_dir: /var/www
    volumes:
      - .:/var/www
  
  database:
    image: mysql:5
    ports:
      - 3306:3306
    volumes:
      - ./application/db:/docker-entrypoint-initdb.d:cached
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: graze
      MYSQL_PASSWORD: graze
      MYSQL_DATABASE: graze

